export const categories = [
    "Beverages",
    "Bottles",
    "Bottles - Britvic",
    "Bottles - Coca cola",
    "Bottles - Energy",
    "Bottles - Others",
    "Bottles - Protein",
    "Bottles - Water/flavoured wate",
    "Cans",
    "Cans - Britvic",
    "Cans - Coca cola",
    "Cans - Energy",
    "Cans - Others",
];
/*
    all cans are 65 mm in diameter (includes monster)
    redbull cans are 50 mm in diameter (some other drinks as well like iced coffees)

*/
export const fakePlanogram = [
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 0,
        "column_id": 0,
        "spiral_number": 0,
        "spiral_size": 10,
        "product_id": 531,
        "product_name": "500MLx24 COCA COLA",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 0,
        "column_id": 1,
        "spiral_number": 1,
        "spiral_size": 10,
        "product_id": 531,
        "product_name": "500MLx24 COCA COLA",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 0,
        "column_id": 2,
        "spiral_number": 2,
        "spiral_size": 10,
        "product_id": 531,
        "product_name": "500MLx24 COCA COLA",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 0,
        "column_id": 3,
        "spiral_number": 3,
        "spiral_size": 10,
        "product_id": 531,
        "product_name": "500MLx24 COCA COLA",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 0,
        "column_id": 4,
        "spiral_number": 4,
        "spiral_size": 10,
        "product_id": 531,
        "product_name": "500MLx24 COCA COLA",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 0,
        "column_id": 5,
        "spiral_number": 5,
        "spiral_size": 10,
        "product_id": 2575,
        "product_name": "500ML COKE ZERO",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 0,
        "column_id": 6,
        "spiral_number": 6,
        "spiral_size": 10,
        "product_id": 521,
        "product_name": "FANTA ORANGE BOTTLES",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 0,
        "column_id": 7,
        "spiral_number": 7,
        "spiral_size": 10,
        "product_id": 521,
        "product_name": "FANTA ORANGE BOTTLES",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 0,
        "column_id": 8,
        "spiral_number": 8,
        "spiral_size": 10,
        "product_id": 521,
        "product_name": "FANTA ORANGE BOTTLES",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 1,
        "column_id": 0,
        "spiral_number": 9,
        "spiral_size": 10,
        "product_id": 532,
        "product_name": "DR PEPPER BOTTLES",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 1,
        "column_id": 1,
        "spiral_number": 10,
        "spiral_size": 10,
        "product_id": 532,
        "product_name": "DR PEPPER BOTTLES",
        "product_category": "Bottles - Coca cola",
        "product_category_id": 7001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 1,
        "column_id": 2,
        "spiral_number": 11,
        "spiral_size": 10,
        "product_id": 1647,
        "product_name": "600ml CHERRY PEPSI M",
        "product_category": "Bottles - Britvic",
        "product_category_id": 7002,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 1,
        "column_id": 3,
        "spiral_number": 12,
        "spiral_size": 10,
        "product_id": 1647,
        "product_name": "600ml CHERRY PEPSI M",
        "product_category": "Bottles - Britvic",
        "product_category_id": 7002,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 1,
        "column_id": 4,
        "spiral_number": 13,
        "spiral_size": 10,
        "product_id": 1647,
        "product_name": "600ml CHERRY PEPSI M",
        "product_category": "Bottles - Britvic",
        "product_category_id": 7002,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 1,
        "column_id": 5,
        "spiral_number": 14,
        "spiral_size": 10,
        "product_id": 2441,
        "product_name": "RUBICON BLACK CHERRY",
        "product_category": "Bottles - Others",
        "product_category_id": 7003,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 1,
        "column_id": 6,
        "spiral_number": 15,
        "spiral_size": 10,
        "product_id": 2441,
        "product_name": "RUBICON BLACK CHERRY",
        "product_category": "Bottles - Others",
        "product_category_id": 7003,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 1,
        "column_id": 7,
        "spiral_number": 16,
        "spiral_size": 10,
        "product_id": 5540,
        "product_name": "RADNOR HILL 500ML",
        "product_category": "Bottles - Water/flavoured wate",
        "product_category_id": 7004,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 1,
        "column_id": 8,
        "spiral_number": 17,
        "spiral_size": 10,
        "product_id": 5540,
        "product_name": "RADNOR HILL 500ML",
        "product_category": "Bottles - Water/flavoured wate",
        "product_category_id": 7004,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 2,
        "column_id": 0,
        "spiral_number": 18,
        "spiral_size": 10,
        "product_id": 4904,
        "product_name": "OASIS SUMMER FRUITS",
        "product_category": "Bottles - Others",
        "product_category_id": 7003,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 2,
        "column_id": 1,
        "spiral_number": 19,
        "spiral_size": 10,
        "product_id": 4904,
        "product_name": "OASIS SUMMER FRUITS",
        "product_category": "Bottles - Others",
        "product_category_id": 7003,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 2,
        "column_id": 2,
        "spiral_number": 20,
        "spiral_size": 10,
        "product_id": 5682,
        "product_name": "JBURST APPLE JUICE",
        "product_category": "Bottles",
        "product_category_id": 7000,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 2,
        "column_id": 3,
        "spiral_number": 21,
        "spiral_size": 10,
        "product_id": 5677,
        "product_name": "JBURST ORANGE JUICE",
        "product_category": "Bottles - Others",
        "product_category_id": 7003,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 2,
        "column_id": 4,
        "spiral_number": 22,
        "spiral_size": 10,
        "product_id": 5677,
        "product_name": "JBURST ORANGE JUICE",
        "product_category": "Bottles - Others",
        "product_category_id": 7003,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 2,
        "column_id": 5,
        "spiral_number": 23,
        "spiral_size": 10,
        "product_id": 4114,
        "product_name": "MONSTER ENERGY",
        "product_category": "Cans - Energy",
        "product_category_id": 13004,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 2,
        "column_id": 6,
        "spiral_number": 24,
        "spiral_size": 10,
        "product_id": 4114,
        "product_name": "MONSTER ENERGY",
        "product_category": "Cans - Energy",
        "product_category_id": 13004,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 2,
        "column_id": 7,
        "spiral_number": 25,
        "spiral_size": 10,
        "product_id": 5756,
        "product_name": "MONSTER LANDO ZERO",
        "product_category": "Cans - Energy",
        "product_category_id": 13004,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 2,
        "column_id": 8,
        "spiral_number": 26,
        "spiral_size": 10,
        "product_id": 6013,
        "product_name": "MONSTER ROSA",
        "product_category": "Cans - Energy",
        "product_category_id": 13004,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 3,
        "column_id": 0,
        "spiral_number": 27,
        "spiral_size": 10,
        "product_id": 509,
        "product_name": "330ML COCA COLA CAN",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 3,
        "column_id": 1,
        "spiral_number": 28,
        "spiral_size": 10,
        "product_id": 509,
        "product_name": "330ML COCA COLA CAN",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 3,
        "column_id": 2,
        "spiral_number": 29,
        "spiral_size": 10,
        "product_id": 509,
        "product_name": "330ML COCA COLA CAN",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 3,
        "column_id": 3,
        "spiral_number": 30,
        "spiral_size": 10,
        "product_id": 534,
        "product_name": "330ML ZERO COKE CANS",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 3,
        "column_id": 4,
        "spiral_number": 31,
        "spiral_size": 10,
        "product_id": 534,
        "product_name": "330ML ZERO COKE CANS",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 3,
        "column_id": 5,
        "spiral_number": 32,
        "spiral_size": 10,
        "product_id": 2773,
        "product_name": "RIO TROPICAL CAN",
        "product_category": "Cans - Others",
        "product_category_id": 13003,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 3,
        "column_id": 6,
        "spiral_number": 33,
        "spiral_size": 10,
        "product_id": 2773,
        "product_name": "RIO TROPICAL CAN",
        "product_category": "Cans - Others",
        "product_category_id": 13003,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 3,
        "column_id": 7,
        "spiral_number": 34,
        "spiral_size": 10,
        "product_id": 819,
        "product_name": "330ML RUBICON CAN",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 3,
        "column_id": 8,
        "spiral_number": 35,
        "spiral_size": 10,
        "product_id": 819,
        "product_name": "330ML RUBICON CAN",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 4,
        "column_id": 0,
        "spiral_number": 36,
        "spiral_size": 10,
        "product_id": 509,
        "product_name": "330ML COCA COLA CAN",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 4,
        "column_id": 1,
        "spiral_number": 37,
        "spiral_size": 10,
        "product_id": 509,
        "product_name": "330ML COCA COLA CAN",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 4,
        "column_id": 2,
        "spiral_number": 38,
        "spiral_size": 10,
        "product_id": 509,
        "product_name": "330ML COCA COLA CAN",
        "product_category": "Cans - Coca cola",
        "product_category_id": 13001,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 4,
        "column_id": 3,
        "spiral_number": 39,
        "spiral_size": 10,
        "product_id": 530,
        "product_name": "330ML PEPSI MAX CAN",
        "product_category": "Cans - Britvic",
        "product_category_id": 13002,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 4,
        "column_id": 4,
        "spiral_number": 40,
        "spiral_size": 10,
        "product_id": 530,
        "product_name": "330ML PEPSI MAX CAN",
        "product_category": "Cans - Britvic",
        "product_category_id": 13002,
        "selection_capacity": 8,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 4,
        "column_id": 5,
        "spiral_number": 41,
        "spiral_size": 10,
        "product_id": 2334,
        "product_name": "RUSH ENERGY DRINK",
        "product_category": "Cans - Energy",
        "product_category_id": 13004,
        "selection_capacity": 10,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 4,
        "column_id": 6,
        "spiral_number": 42,
        "spiral_size": 10,
        "product_id": 2334,
        "product_name": "RUSH ENERGY DRINK",
        "product_category": "Cans - Energy",
        "product_category_id": 13004,
        "selection_capacity": 10,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 4,
        "column_id": 7,
        "spiral_number": 43,
        "spiral_size": 10,
        "product_id": 2334,
        "product_name": "RUSH ENERGY DRINK",
        "product_category": "Cans - Energy",
        "product_category_id": 13004,
        "selection_capacity": 10,
        "max_fill": 0
    },
    {
        "plan_id": 9949,
        "machine_id": 5415,
        "layout": "9,9,9,9,9",
        "row_id": 4,
        "column_id": 8,
        "spiral_number": 44,
        "spiral_size": 10,
        "product_id": 2334,
        "product_name": "RUSH ENERGY DRINK",
        "product_category": "Cans - Energy",
        "product_category_id": 13004,
        "selection_capacity": 10,
        "max_fill": 0
    }
]