export { styles };

const styles: { [key: string]: React.CSSProperties } = {
  body: {
    fontFamily:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: "7rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
  },
  adminTrigger: {
    position: "fixed",
    top: 0,
    left: 0,
    width: 60,
    height: 60,
    zIndex: 9999,
    opacity: 0,
    backgroundColor: "rgba(255, 0, 0, 0.5)",
  },
  topContainer: {
    position: "fixed",
    top: 0,
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 1100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "var(--theme-secondary, #181A20)",
    boxShadow: "0px 2px 15px rgba(0, 0, 0, 0.52)",
    borderRadius: "50px",
    padding: "0.5rem 0.5rem",
    marginTop: "1rem",
    maxWidth: "90%",
  },
  header: {
    width: "100%",
    textAlign: "center",
    margin: 0,
  },
  categoryIndicatorContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: 0,
    overflowX: "auto",
  },
  noProductsMessage: {
    textAlign: "center",
    color: "var(--theme-text, #d4d4d4)",
    fontSize: "1.2rem",
    marginTop: "2rem",
    padding: "2rem",
  },
  productsSection: {
    display: "flex",
    flexWrap: "wrap",
    gap: "1rem",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    maxWidth: "900px",
    margin: "0 auto 2rem auto",
    marginTop: "1rem",
    marginBottom: "8rem",
  },
  paymentSection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "4rem",
    padding: "0.5rem 0 1rem",
    justifyContent: "center",
  },
  statusIcon: {
    fontSize: "3.5rem",
    lineHeight: 1,
  },
  statusMessage: {
    textAlign: "center",
    color: "#d4d4d4",
    margin: 0,
    fontSize: "1.5rem",
    minHeight: "1.4rem",
    maxWidth: "280px",
  },
  nfcNotification: {
    position: "fixed",
    bottom: "2rem",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: "#c03a2b",
    color: "#fff",
    padding: "0.5rem 1.5rem",
    borderRadius: "0.5rem",
    zIndex: 99999,
    fontSize: "1rem",
    fontWeight: 600,
    boxShadow: "0 4px 16px rgba(0,0,0,0.45)",
    pointerEvents: "none",
    letterSpacing: "0.01em",
  },
};
